// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: egrpc.proto

package egrpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TestResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Mes     string `protobuf:"bytes,2,opt,name=mes,proto3" json:"mes,omitempty"`
}

func (x *TestResponse) Reset() {
	*x = TestResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_egrpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestResponse) ProtoMessage() {}

func (x *TestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_egrpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestResponse.ProtoReflect.Descriptor instead.
func (*TestResponse) Descriptor() ([]byte, []int) {
	return file_egrpc_proto_rawDescGZIP(), []int{0}
}

func (x *TestResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestResponse) GetMes() string {
	if x != nil {
		return x.Mes
	}
	return ""
}

var File_egrpc_proto protoreflect.FileDescriptor

var file_egrpc_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x65,
	0x67, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x3a, 0x0a, 0x0c, 0x54, 0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x65, 0x73, 0x32, 0x3e, 0x0a,
	0x05, 0x45, 0x47, 0x52, 0x50, 0x43, 0x12, 0x35, 0x0a, 0x04, 0x54, 0x65, 0x73, 0x74, 0x12, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x65, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x54,
	0x65, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a,
	0x07, 0x2e, 0x3b, 0x65, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_egrpc_proto_rawDescOnce sync.Once
	file_egrpc_proto_rawDescData = file_egrpc_proto_rawDesc
)

func file_egrpc_proto_rawDescGZIP() []byte {
	file_egrpc_proto_rawDescOnce.Do(func() {
		file_egrpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_egrpc_proto_rawDescData)
	})
	return file_egrpc_proto_rawDescData
}

var file_egrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_egrpc_proto_goTypes = []interface{}{
	(*TestResponse)(nil),  // 0: egrpc.TestResponse
	(*emptypb.Empty)(nil), // 1: google.protobuf.Empty
}
var file_egrpc_proto_depIdxs = []int32{
	1, // 0: egrpc.EGRPC.Test:input_type -> google.protobuf.Empty
	0, // 1: egrpc.EGRPC.Test:output_type -> egrpc.TestResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_egrpc_proto_init() }
func file_egrpc_proto_init() {
	if File_egrpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_egrpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_egrpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_egrpc_proto_goTypes,
		DependencyIndexes: file_egrpc_proto_depIdxs,
		MessageInfos:      file_egrpc_proto_msgTypes,
	}.Build()
	File_egrpc_proto = out.File
	file_egrpc_proto_rawDesc = nil
	file_egrpc_proto_goTypes = nil
	file_egrpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EGRPCClient is the client API for EGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EGRPCClient interface {
	Test(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TestResponse, error)
}

type eGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewEGRPCClient(cc grpc.ClientConnInterface) EGRPCClient {
	return &eGRPCClient{cc}
}

func (c *eGRPCClient) Test(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*TestResponse, error) {
	out := new(TestResponse)
	err := c.cc.Invoke(ctx, "/egrpc.EGRPC/Test", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EGRPCServer is the server API for EGRPC service.
type EGRPCServer interface {
	Test(context.Context, *emptypb.Empty) (*TestResponse, error)
}

// UnimplementedEGRPCServer can be embedded to have forward compatible implementations.
type UnimplementedEGRPCServer struct {
}

func (*UnimplementedEGRPCServer) Test(context.Context, *emptypb.Empty) (*TestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Test not implemented")
}

func RegisterEGRPCServer(s *grpc.Server, srv EGRPCServer) {
	s.RegisterService(&_EGRPC_serviceDesc, srv)
}

func _EGRPC_Test_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EGRPCServer).Test(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/egrpc.EGRPC/Test",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EGRPCServer).Test(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _EGRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "egrpc.EGRPC",
	HandlerType: (*EGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Test",
			Handler:    _EGRPC_Test_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egrpc.proto",
}
